import asyncio, os, subprocess, sys, time
from playwright.async_api import async_playwright
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "site"))
TEST = os.path.abspath(os.path.dirname(__file__))
MOCK = open(os.path.join(TEST, "mock-supabase.js")).read()
CFG = 'window.TAPO_CONFIG = {SUPABASE_URL: "https://test.supabase.co", SUPABASE_ANON_KEY: "test"};'
async def main():
    srv = subprocess.Popen([sys.executable, "-m", "http.server", "8765", "-d", ROOT], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(1)
    base = "http://127.0.0.1:8765/"
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width':1280,'height':800})
        await ctx.add_init_script(MOCK)
        async def route(r):
            u = r.request.url
            if u.endswith("/config.js"): return await r.fulfill(body=CFG, content_type="application/javascript")
            if u.startswith(base): return await r.continue_()
            return await r.abort()
        await ctx.route("**/*", route)
        errs = []
        pg = await ctx.new_page()
        pg.on('pageerror', lambda e: errs.append('PAGEERROR ' + str(e)))
        pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' and 'ERR_FAILED' not in m.text and 'Failed to load' not in m.text else None)
        await pg.goto(base + "index.html")
        await pg.wait_for_selector('#loading', state='hidden', timeout=60000)
        await pg.wait_for_timeout(500)
        print('1 auth view:', await pg.evaluate('authView'), 'visible:', await pg.is_visible('#auth'))
        await pg.screenshot(path=os.path.join(TEST,'shots/')+'01_login.png')
        # sign up host
        await pg.click('text=Create account')
        await pg.fill('#username', 'Greg'); await pg.fill('#email', 'greg@example.com'); await pg.fill('#newpw', 'globetrot1'); await pg.fill('#newpw2', 'globetrot1')
        await pg.screenshot(path=os.path.join(TEST,'shots/')+'02_signup.png')
        await pg.click('form >> text=Create account')
        await pg.wait_for_timeout(400)
        print('2 after signup:', await pg.evaluate('authView'))
        await pg.screenshot(path=os.path.join(TEST,'shots/')+'03_confirm.png')
        # log in with username, wrong password first
        await pg.click('text=Back to log in')
        await pg.fill('#login', 'greg'); await pg.fill('#password', 'nope'); await pg.click('form >> text=Log in'); await pg.wait_for_timeout(300)
        print('3 wrong pw note:', await pg.evaluate('document.querySelector("#authcard .note")?.textContent'))
        await pg.fill('#login', 'greg'); await pg.fill('#password', 'globetrot1'); await pg.click('form >> text=Log in'); await pg.wait_for_timeout(800)
        print('4 logged in:', await pg.is_hidden('#auth'), await pg.evaluate('net.me && [net.me.username, net.me.is_admin]'))
        # second player via direct mock signup so rankings/duels have someone
        await pg.evaluate('''(async()=>{const c=window.supabase.createClient(); await c.auth.signUp({email:"maya@example.com",password:"mayamaya1",options:{data:{username:"Maya",avatar:"🦊",color:"#C58BFF"}}}); })()''')
        await pg.evaluate('loadAll()')
        for i in range(5):
            cx = await pg.evaluate('gcx'); cy = await pg.evaluate('gcy')
            await pg.mouse.click(cx + 25, cy - 20); await pg.wait_for_timeout(150)
            await pg.click('#action'); await pg.wait_for_timeout(1250)
            await pg.click('#action'); await pg.wait_for_timeout(700)
        await pg.wait_for_timeout(600)
        print('5 summary stats:', await pg.evaluate('document.getElementById("stats").innerText.replace(/\\n/g," ")'))
        await pg.screenshot(path=os.path.join(TEST,'shots/')+'04_summary.png')
        await pg.click('#again'); await pg.wait_for_timeout(400)
        await pg.click('#nb-rank'); await pg.wait_for_timeout(300); await pg.screenshot(path=os.path.join(TEST,'shots/')+'05_rank.png'); await pg.click('#sheetx')
        await pg.click('#nb-me'); await pg.wait_for_timeout(300); await pg.screenshot(path=os.path.join(TEST,'shots/')+'06_profile.png')
        print('6 host link:', await pg.is_visible('text=Open the host control panel'), 'nav host btn:', await pg.is_visible('#nb-admin'))
        await pg.click('#sheetx')
        # challenge Maya
        await pg.click('#nb-duel'); await pg.wait_for_timeout(300)
        await pg.click('.board li >> text=Duel'); await pg.wait_for_timeout(800)
        print('7 duel mode:', await pg.evaluate('state.mode'), await pg.evaluate('document.getElementById("vs").textContent'))
        # control panel
        ap = await ctx.new_page()
        ap.on('pageerror', lambda e: errs.append('ADMIN PAGEERROR ' + str(e)))
        await ap.goto(base + "admin.html"); await ap.wait_for_timeout(600)
        await ap.screenshot(path=os.path.join(TEST,'shots/')+'07_gate.png')
        await ap.fill('#hostpw', 'wrong'); await ap.click('text=Open control panel'); await ap.wait_for_timeout(300)
        print('8 gate wrong pw:', await ap.evaluate('document.querySelector("#gatecard .note")?.textContent'))
        await ap.fill('#hostpw', 'globetrot1'); await ap.click('text=Open control panel'); await ap.wait_for_timeout(700)
        await ap.screenshot(path=os.path.join(TEST,'shots/')+'08_overview.png', full_page=True)
        await ap.click('#tabs >> text=Players'); await ap.wait_for_timeout(300)
        await ap.screenshot(path=os.path.join(TEST,'shots/')+'09_players.png', full_page=True)
        await ap.click('.admintbl tbody tr >> text=Maya'); await ap.wait_for_timeout(500)
        await ap.click('text=Suspend player'); await ap.wait_for_timeout(300)
        await ap.fill('#rename', 'Maya R'); await ap.click('text=Rename'); await ap.wait_for_timeout(300)
        await ap.click('text=Send reset email'); await ap.wait_for_timeout(200)
        print('9 reset sent to:', await ap.evaluate('window.__resetSentTo'))
        await ap.screenshot(path=os.path.join(TEST,'shots/')+'10_player.png', full_page=True)
        print('10 after actions:', await ap.evaluate('JSON.stringify(JSON.parse(localStorage.mockdb).profiles.map(p=>[p.username,p.banned,p.is_admin]))'))
        await ap.fill('#deltype', 'Maya R'); await ap.click('button.dangerbtn:has-text("Delete account")'); await ap.wait_for_timeout(500)
        print('11 players after delete:', await ap.evaluate('JSON.parse(localStorage.mockdb).profiles.map(p=>p.username).join(",")'))
        await ap.click('#tabs >> text=Settings'); await ap.wait_for_timeout(300)
        await ap.click('text=Generate'); await ap.fill('#announce', 'Duel week! Challenge someone.'); await ap.click('#signups')
        await ap.click('text=Save settings'); await ap.wait_for_timeout(400)
        print('12 settings:', await ap.evaluate('JSON.stringify(JSON.parse(localStorage.mockdb).settings)'))
        await ap.screenshot(path=os.path.join(TEST,'shots/')+'11_settings.png', full_page=True)
        await ap.click('#tabs >> text=Duels'); await ap.wait_for_timeout(300); await ap.screenshot(path=os.path.join(TEST,'shots/')+'12_duels.png', full_page=True)
        # phone views
        ph = await b.new_context(viewport={'width':390,'height':844}, device_scale_factor=2)
        await ph.add_init_script(MOCK); await ph.route("**/*", route)
        pp = await ph.new_page(); await pp.goto(base + "index.html"); await pp.wait_for_selector('#loading', state='hidden', timeout=60000); await pp.wait_for_timeout(400)
        await pp.screenshot(path=os.path.join(TEST,'shots/')+'13_phone_login.png')
        await pp.evaluate('localStorage.setItem("mockdb", JSON.stringify(Object.assign(JSON.parse(localStorage.getItem("mockdb")||"{}"))))')
        await ph.close()
        print('errors:', errs[:10])
        await b.close()
    srv.terminate()
asyncio.run(main())
